# Generated by Django 3.0.8 on 2020-07-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='bigtitle',
        ),
    ]
