# Generated by Django 3.0.8 on 2020-07-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200712_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='bigtitle',
            new_name='title',
        ),
    ]
